API_ROOT = "/api"

PATH_GET_MEETING = API_ROOT + "/projects/{project_id}/meetings/{meeting_id}"
PATH_LIST_DECISIONS = API_ROOT + "/projects/{project_id}/decisions"
PATH_GET_DECISION = API_ROOT + "/projects/{project_id}/decisions/{decision_id}"
PATH_CREATE_DECISION = API_ROOT + "/projects/{project_id}/decisions"
PATH_PATCH_DECISION = API_ROOT + "/projects/{project_id}/decisions/{decision_id}"
PATH_LINK_MEETING = API_ROOT + "/projects/{project_id}/decisions/{decision_id}/link_meeting"
PATH_CREATE_THREAD = API_ROOT + "/projects/{project_id}/decisions/{decision_id}/chat/thread"
PATH_POST_MESSAGE = API_ROOT + "/chat/threads/{thread_id}/messages"
PATH_GET_MESSAGE = API_ROOT + "/chat/threads/{thread_id}/messages/{message_id}"
PATH_MEETING_LOG = API_ROOT + "/projects/{project_id}/meetings/{meeting_id}/logs"
PATH_ACTIONS_BULK = API_ROOT + "/projects/{project_id}/decisions/{decision_id}/actions/bulk"
PATH_NOTIFY = API_ROOT + "/projects/{project_id}/notifications"
PATH_CALLBACK = API_ROOT + "/internal/agent/callback"
