param(
  [string]$Environment = "mvp",
  [switch]$WriteWebEnv
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Assert-Command {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command not found: $Name"
  }
}

function Write-DotEnvFile {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][System.Collections.IDictionary]$Values,
    [Parameter(Mandatory = $true)][string]$Title
  )

  $lines = @(
    "# $Title",
    "# Generated by infra/scripts/sync-local-env.ps1",
    "# Source of truth: infra/terraform outputs",
    "# This file may be overwritten."
  )

  foreach ($key in $Values.Keys) {
    $lines += "$key=$($Values[$key])"
  }

  Set-Content -Path $Path -Value ($lines -join "`n") -Encoding utf8
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$infraDir = Split-Path -Parent $scriptDir
$repoRoot = Split-Path -Parent $infraDir
$terraformDir = Join-Path $infraDir "terraform"

Assert-Command -Name "terraform"

$raw = & terraform "-chdir=$terraformDir" output -json
if ($LASTEXITCODE -ne 0) {
  throw "terraform output -json failed."
}

$outputs = $raw | ConvertFrom-Json
if (-not ($outputs.PSObject.Properties.Name -contains "local_runtime_hints")) {
  throw "Terraform output 'local_runtime_hints' is missing. Run terraform apply/plan first."
}

$hints = $outputs.local_runtime_hints.value
$apiHints = $hints.api
$agentHints = $hints.agent

$apiPath = Join-Path $repoRoot "apps/api/.env.infra.local"
$agentPath = Join-Path $repoRoot "apps/agent/.env.infra.local"

$apiValues = [ordered]@{
  FIRESTORE_PROJECT_ID            = $apiHints.FIRESTORE_PROJECT_ID
  GOOGLE_CLOUD_PROJECT            = $apiHints.GOOGLE_CLOUD_PROJECT
  DISABLE_CLOUD_TASKS             = $apiHints.DISABLE_CLOUD_TASKS
  CLOUD_TASKS_QUEUE               = $apiHints.CLOUD_TASKS_QUEUE
  CLOUD_TASKS_LOCATION            = $apiHints.CLOUD_TASKS_LOCATION
  TASK_OIDC_SERVICE_ACCOUNT_EMAIL = $apiHints.TASK_OIDC_SERVICE_ACCOUNT_EMAIL
  AGENT_TASK_OIDC_AUDIENCE        = $apiHints.AGENT_TASK_OIDC_AUDIENCE
  AGENT_TASK_URL_MEETING          = $apiHints.AGENT_TASK_URL_MEETING
  AGENT_TASK_URL_REPLY            = $apiHints.AGENT_TASK_URL_REPLY
  AGENT_TASK_URL_ACTIONS          = $apiHints.AGENT_TASK_URL_ACTIONS
  AGENT_CALLBACK_TOKEN            = "change-me"
}

$agentValues = [ordered]@{
  API_BASE_URL        = $agentHints.API_BASE_URL
  API_AUDIENCE        = $agentHints.API_AUDIENCE
  TASK_AUTH_MODE      = $agentHints.TASK_AUTH_MODE
  TASK_OIDC_AUDIENCE  = $agentHints.TASK_OIDC_AUDIENCE
  AGENT_CALLBACK_TOKEN = "change-me"
  LOG_LEVEL           = "INFO"
}

Write-DotEnvFile -Path $apiPath -Values $apiValues -Title "apps/api local env generated from infra ($Environment)"
Write-DotEnvFile -Path $agentPath -Values $agentValues -Title "apps/agent local env generated from infra ($Environment)"

if ($WriteWebEnv.IsPresent) {
  $webPath = Join-Path $repoRoot "apps/web/.env.infra.local"
  $webValues = [ordered]@{
    KIMEBOARD_API_BASE_URL = $agentHints.API_BASE_URL
    NEXT_PUBLIC_API_DATA_MODE = "production"
  }
  Write-DotEnvFile -Path $webPath -Values $webValues -Title "apps/web local env generated from infra ($Environment)"
  Write-Host "Generated: $webPath"
}

Write-Host "Generated: $apiPath"
Write-Host "Generated: $agentPath"
Write-Host "AGENT_CALLBACK_TOKEN is a placeholder. Replace with your Secret Manager value."
